apiVersion: v1
kind: Secret
metadata:
  name: new-deploy
  labels:
    app: new-deploy
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  my_secret_key: {{ .Values.secret_sandbox_new-deploy | b64enc | quote }}